
languageCode = "tr"
contentdir = "content"
publishdir = "public"
builddrafts = false
baseUrl = "https://phpanaliz.com/"
canonifyurls = true
title = "PHP Analiz - Uğur KAZDAL"
author = "Uğur KAZDAL"
theme = "pixyll"
pluralizelisttitles = false

[indexes]
  category = "konular"
  tag = "tags"

[params]
  search_engine = true
  google_analytics_id = "UA-101420301-2"
  paginate = true
  author = "Uğur KAZDAL"